# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='user',
        ),
    ]
