# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_auto_20170408_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
